### ISSUE TITLE
CRAN package archived

### ISSUE THREAD

**Issue by muschellij2** [paulhibbing/Sojourn#5]
Looks like it was done in April: https://cran.r-project.org/web//packages//Sojourn/index.html

**Comment by paulhibbing** [comment]
This was a side effect of a dependency chain breakdown. `matchingMarkets` was archived, which led to the archiving of `PAutilities`, which led to the archiving of `Sojourn`. It looks like `matchingMarkets` is back up, as of a few weeks ago. But I don't have immediate plans for re-releases on CRAN.
